services:
  backend:
    build: ./backend/
    environment:
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_ID=${CLIENT_ID}

  frontend:
    build: ./frontend/

  proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80